server:
  port: 0

spring:
  data:
    mongodb:
      uri: mongodb://mongodb/finalBack
  zipkin:
    base-url: http://zipkin/
    enabled: true

  rabbitmq:
    username: guest
    password: guest
    host: rabbit-mq

queue:
  movie:
    name: movieQueue
  serie:
    name: serieQueue
  catalog:
    name: catalogQueue

eureka:
  client:
    service-url:
      defaultZone: http://eureka-server/eureka/
    fetch-registry: true
    register-with-eureka: true

resilience4j:
  circuitbreaker:
    instances:
      movie:
        slidingWindowType: COUNT_BASED
        slidingWindowSize: 5
        failureRateThreshold: 50
        waitDurationInOpenState: 15000
        permittedNumberOfCallsInHalfOpenState: 3
        registerHealthIndicator: true
        allowHealthIndicatorToFail: false
        automaticTransitionFromOpenToHalfOpenEnabled: true

      serie:
        slidingWindowType: COUNT_BASED
        slidingWindowSize: 5
        failureRateThreshold: 50
        waitDurationInOpenState: 15000
        permittedNumberOfCallsInHalfOpenState: 3
        registerHealthIndicator: true
        allowHealthIndicatorToFail: false
        automaticTransitionFromOpenToHalfOpenEnabled: true

  retry:
    instances:
      movies:
        waitDuration: 1000
        maxAttempts: 3
        retryExceptions:
          - feign.FeignException$InternalServerError

      serie:
        waitDuration: 1000
        maxAttempts: 3
        retryExceptions:
          - feign.FeignException$InternalServerError
