server:
  port: 8085

spring:
  cloud:
    gateway:
      routes:
        - id: movie-service
          uri: lb://movie-service
          predicates:
            - Path=/movie/**

        - id: serie-service
          uri: lb://serie-service
          predicates:
            - Path=/serie/**

        - id: catalog-service
          uri: lb://catalog-service
          predicates:
            - Path=/catalog/**

      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
      default-filters:
        - AddRequestHeader=user-request-header, custom-user-request-header
        - AddResponseHeader=user-response-header, custom-user-response-header
        - LogFilter

  zipkin:
    base-url: http://localhost:9411/
    enabled: true

eureka:
  instance:
    hostname: localhost
    instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}
    prefer-ip-address: true
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
    fetch-registry: true
    register-with-eureka: true

