server:
  port : 8083
spring:
  data:
    mongodb:
      uri: mongodb://mongodb:27017/finalBack
  zipkin:
    base-url: http://zipkin:9411/
    enabled: true

  rabbitmq:
    username: guest
    password: guest
    host: rabbit-mq

queue:
  movie:
    name: movieQueue
    
eureka:
  client:
    service-url:
      defaultZone: http://eureka-server:8761/eureka/
