server:
  port : 0
spring:
  data:
    mongodb:
      uri: mongodb://mongodb/finalBack
  zipkin:
    base-url: http://zipkin/
    enabled: true

  rabbitmq:
    username: guest
    password: guest
    host: rabbit-mq

queue:
  movie:
    name: movieQueue
    
eureka:
  client:
    service-url:
      defaultZone: http://eureka-server/
